/**
 * Gemini AI Service
 * AI 기반 코드 생성
 */

export interface CodeFile {
  path: string;
  content: string;
  type: 'create' | 'update' | 'delete';
}

export interface VibeResponse {
  message: string;
  files: CodeFile[];
  projectDescription: string;
  suggestedCommitMessage: string;
  nextSteps: string[];
}

const GEMINI_API_BASE_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent';

const SYSTEM_PROMPT = `
당신은 'Vibers' 플랫폼의 AI 코딩 에이전트입니다.
사용자의 요청을 듣고 실제 동작하는 코드를 생성하는 것이 목표입니다.

[핵심 원칙]
1. 프로젝트 전체를 관리합니다 (단일 파일이 아닌 여러 파일)
2. 웹 표준을 준수합니다 (React, Next.js, Tailwind CSS)
3. 각 파일은 'create', 'update', 'delete' 중 하나의 타입을 가집니다
4. 즉시 실행 가능한 완전한 코드를 제공합니다

[출력 형식]
반드시 다음 JSON 구조를 따르십시오:
{
  "message": "사용자에게 보낼 친절한 메시지",
  "files": [
    {
      "path": "파일 경로 (예: src/components/Button.tsx)",
      "content": "완전한 파일 내용",
      "type": "create | update | delete"
    }
  ],
  "projectDescription": "현재 프로젝트 기능 요약",
  "suggestedCommitMessage": "feat: 버튼 컴포넌트 추가",
  "nextSteps": ["다음 단계 제안 1", "제안 2"]
}

[중요] 반드시 유효한 JSON만 출력하세요. 마크다운이나 다른 텍스트는 포함하지 마세요.
`;

/**
 * Call Gemini API to generate code
 */
export async function generateCode(
  userPrompt: string,
  apiKey: string,
  projectContext: string = ''
): Promise<VibeResponse> {
  if (!apiKey) {
    throw new Error('Gemini API key is required');
  }

  try {
    const fullPrompt = projectContext
      ? `${SYSTEM_PROMPT}\n\n[프로젝트 컨텍스트]\n${projectContext}\n\n[사용자 요청]\n${userPrompt}`
      : `${SYSTEM_PROMPT}\n\n[사용자 요청]\n${userPrompt}`;

    const response = await fetch(`${GEMINI_API_BASE_URL}?key=${apiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: fullPrompt,
              },
            ],
          },
        ],
        generationConfig: {
          temperature: 0.7,
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 8192,
        },
      }),
    });

    if (!response.ok) {
      const error = (await response.json()) as { error?: { message?: string } };
      throw new Error(`Gemini API error: ${error.error?.message || response.statusText}`);
    }

    const data = (await response.json()) as {
      candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }>;
    };

    // Extract generated text
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!generatedText) {
      throw new Error('No response from Gemini API');
    }

    // Parse JSON response
    let vibeResponse: VibeResponse;

    try {
      // Try to extract JSON from markdown code blocks if present
      const jsonMatch = generatedText.match(/```json\n([\s\S]*?)\n```/) ||
                       generatedText.match(/```\n([\s\S]*?)\n```/);

      const jsonText = jsonMatch ? jsonMatch[1] : generatedText;
      vibeResponse = JSON.parse(jsonText);
    } catch (parseError) {
      console.error('Failed to parse Gemini response as JSON:', generatedText);

      // Fallback: create a simple response
      vibeResponse = {
        message: '코드를 생성했습니다!',
        files: [
          {
            path: 'README.md',
            content: `# Generated Code\n\n${generatedText}`,
            type: 'create',
          },
        ],
        projectDescription: '프로젝트가 생성되었습니다.',
        suggestedCommitMessage: 'feat: AI generated code',
        nextSteps: ['코드를 검토하세요', '필요한 수정을 하세요'],
      };
    }

    return vibeResponse;
  } catch (error: any) {
    console.error('Gemini API error:', error);
    throw new Error(`코드 생성 실패: ${error.message}`);
  }
}

/**
 * Simulate code generation (for testing without API key)
 */
export function simulateCodeGeneration(userPrompt: string): VibeResponse {
  return {
    message: `"${userPrompt}" 요청을 받았습니다! AI 코드를 생성했어요. 🎨`,
    files: [
      {
        path: 'src/components/Example.tsx',
        content: `import React from 'react';

export default function Example() {
  return (
    <div className="p-6 bg-gradient-to-r from-green-400 to-blue-500 rounded-lg">
      <h1 className="text-2xl font-bold text-white">
        ${userPrompt}
      </h1>
      <p className="text-white/80 mt-2">
        Generated by Vibers AI
      </p>
    </div>
  );
}`,
        type: 'create',
      },
      {
        path: 'README.md',
        content: `# ${userPrompt}\n\nThis project was generated by Vibers AI.\n\n## Features\n\n- Auto-generated component\n- Tailwind CSS styling\n- Ready to use\n\n## Usage\n\n\`\`\`tsx\nimport Example from './src/components/Example';\n\nfunction App() {\n  return <Example />;\n}\n\`\`\``,
        type: 'create',
      },
    ],
    projectDescription: `${userPrompt}을(를) 구현한 프로젝트입니다.`,
    suggestedCommitMessage: `feat: ${userPrompt} 구현`,
    nextSteps: [
      '컴포넌트 스타일 커스터마이즈',
      '추가 기능 구현',
      'TypeScript 타입 개선',
    ],
  };
}
